# Generated by Django 2.2.4 on 2020-12-23 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_auto_20201215_2041'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'permissions': [('can_delete', 'Delete item')]},
        ),
    ]
